version: 2

sources:
  - name: coffee_shop
    project: analytics-engineers-club
    tables:
      - name: customers
        columns:
          - name: id
            tests:
              - unique
              - not_null

      - name: orders
        columns:
          - name: id
            tests:
              - unique
              - not_null
          - name: customer_id
            tests:
              - relationships:
                  to: source('coffee_shop', 'customers')
                  field: id
          
